USE COMPANY_3;

CREATE TABLE EMPLOYEE (
	Ssn NVARCHAR(10) PRIMARY KEY,
	Fname NVARCHAR (20),
	Lname NVARCHAR(20),
	Bdate DATE,
	EAddress NVARCHAR(50),
	Sex bit
)

CREATE TABLE DEPARTMENT (
	DSsn NVARCHAR(10) PRIMARY KEY,
	DName NVARCHAR(20),
	Dlocation NVARCHAR(50),
	DNumber NVARCHAR(10) 
)

CREATE TABLE PROJECT (
	
)